#!/bin/bash -e

#we install the apache virtual host config for kanopya web ui
cp /opt/kanopya/ui/web/virtualhost.conf /etc/apache2/sites-available/default || true
mkdir /var/log/apache2/kanopya || true
service apache2 restart || true
