#! /bin/bash
### BEGIN INIT INFO
# Provides:           kanopya-front
# Required-Start:     mysql rabbitmq-server
# Required-Stop:      $network $remote_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Kanopya Web interface service
# Description:        Kanopya Web interface service using Starman and Plackup
### END INIT INFO

set -e

. /lib/lsb/init-functions

[ -x "/usr/bin/plackup" ] && DAEMON="/usr/bin/plackup" || DAEMON="/usr/local/bin/plackup"
NAME="Kanopya Web UI"
PIDFILE="/var/run/kanopya-front.pid"
PORT=5000
WORKERS=10
DANCER_DIR="/opt/kanopya/ui/Frontend"
DANCER_APP="$DANCER_DIR/bin/app.pl"
SESSIONS_DIR="/tmp/kanopya-sessions"
lockfile="/var/lock/plackup.front_kanopya"
RETVAL=0

test -x "$DAEMON" || exit 1

# Defaults
export PERL5LIB=\
/opt/kanopya/lib/common:\
/opt/kanopya/lib/administrator:\
/opt/kanopya/lib/monitor:\
/opt/kanopya/lib/executor:\
/opt/kanopya/lib/external:\
/opt/kanopya/lib/external/NetApp:\
/opt/kanopya/lib/orchestrator:\
/opt/kanopya/lib/mock

KANOPYA_FRONT_RUN=yes
KANOPYA_FRONT_OPTS="-E production -p $PORT -s Starman --pid=$PIDFILE --workers $WORKERS --user=kanopya -D -a $DANCER_APP"

# Reads config file (will override defaults above)
[ -r /etc/default/kanopya ] && . /etc/default/kanopya

RUN_DAEMON=$KANOPYA_FRONT_RUN
DAEMON_OPTS=$KANOPYA_FRONT_OPTS

start() {
    echo -n "Starting $NAME"
    pidofproc -p $PIDFILE $DAEMON > /dev/null && status=0 || status=$?

    if [ $status == 0 ]; then
        RETVAL=1
    else
        if [ ! -e $SESSIONS_DIR ]; then
            mkdir -p $SESSIONS_DIR
            chown kanopya.kanopya $SESSIONS_DIR
        fi

        if [ "$RUN_DAEMON" = "yes" ]; then
            start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS
            RETVAL=$?
        fi
    fi

    [ $RETVAL == 0 ] && log_success_msg || log_failure_msg
}

stop() {
    echo -n "Stopping $NAME"
    pidofproc -p $PIDFILE $DAEMON > /dev/null && status=0 || status=$?

    if [ $status == 0 ]; then
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        if [ -f $PIDFILE ]; then
            rm $PIDFILE
        fi
    else
        RETVAL=1
    fi

    [ $RETVAL == 0 ] && log_success_msg || log_failure_msg
}

status() {
    pidofproc -p $PIDFILE $DAEMON > /dev/null && status=0 || status=$?

    if [ $status == 0 ]; then
        echo "$NAME is running"
    else
        echo "$NAME is not running"
    fi
    RETVAL=$status
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit $RETVAL
