#!/bin/sh
### BEGIN INIT INFO
# Provides:           kanopya-front
# Required-Start:     mysql
# Required-Stop:      $network $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Kanopya web interface server
# Description:        Kanopya web interface using Starman server and plackup
### END INIT INFO

set -e

. /lib/lsb/init-functions

PID="/var/run/plackup.front_kanopya.pid"
PORT=5000
WORKERS=10
DANCER_DIR="/opt/kanopya/ui/Frontend"
DANCER_APP="$DANCER_DIR/bin/app.pl"
SESSIONS_DIR="/tmp/kanopya-sessions"

plackup="/usr/bin/plackup"
plackup_args="-E production -p $PORT -s Starman --pid=$PID --workers $WORKERS --user=kanopya -D"
website="Kanopya"

lockfile="/var/lock/plackup.front_kanopya"

PERL5LIB=\
/opt/kanopya/lib/monitor/:\
/opt/kanopya/lib/administrator/:\
/opt/kanopya/lib/executor/:\
/opt/kanopya/lib/external/:\
/opt/kanopya/lib/orchestrator/:\
/opt/kanopya/lib/common
export PERL5LIB

#If plackup install with cpan
if [ ! -e "$plackup" ]
then
    plackup="/usr/local/bin/plackup"
fi

start() {
    [ -x $plackup ] || exit 5
    [ -f $DANCER_APP ] || exit 6
    if [ ! -e $SESSIONS_DIR ]; then
      mkdir -p $SESSIONS_DIR
      chown kanopya.kanopya $SESSIONS_DIR
    fi

    echo -n "Starting $website: "
    $plackup $plackup_args -a $DANCER_APP 2>&1 > /dev/null
    retval=$?
    if [ $retval -eq 0 ]; then
        log_success_msg "$website started"
        touch $lockfile
    else
        log_failure_msg "Unable to start"
    fi
    echo
    return $retval
}

stop() {
    echo -n "Stopping $website: "
    rm -rf $SESSIONS_DIR &> /dev/null
    if [ -f $PID ]; then
        kill `cat $PID` 2>&1 > /dev/null
        retval=$?
        [ $retval -eq 0 ] && rm -f $lockfile $PID
        echo
        return $retval
    fi
    log_failure_msg "pid $PID not found"
    echo
    return 0
}

restart() {
    stop
    start
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac

exit 0
