#!/usr/bin/perl -w
# kanopya-rulesengine.pl - This is the main script to run kanopya orchestration rules engine.

#    Copyright © 2013 Hedera Technology SAS
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Maintained by Dev Team of Hedera Technology <dev@hederatech.com>.
# Created 04 March 2013

=head1 NAME

kanopya-rulesengine - Rules Engine

=head1 SYNOPSIS

	$ ./kanopya-rulesengine

=head1 DESCRIPTION

rulesengine is the main script to run Kanopya rules engine.
Rules Engine evaluate rules and apply associated workflow.

=head1 METHODS

=cut

use strict;
use warnings;
use RulesEngine;
use Kanopya::Config;
use Log::Log4perl "get_logger";

my $dir = Kanopya::Config::getKanopyaDir();
Log::Log4perl->init($dir . '/conf/rulesengine-log.conf');
my $log = get_logger("");


my $running = 1;

sub signalHandler {
	my $sig = shift;
	$log->info($sig." received : stopping main loop");
	$running = 0;
}

$SIG{TERM} = \&signalHandler;


eval	{
	my $rulesengine = RulesEngine->new();
	$log->info("Starting main loop");
	# enter in the main loop and continue while $$running is true
	$rulesengine->run(\$running);
};
if ($@) {
	my $ex = $@;
	$log->error("error in rulesengine instanciation: $ex");
	die "Catch error in rulesengine instanciation: $ex";
};

$log->info("kanopya-rulesengine end.");


__END__

=head1 AUTHOR

Copyright (c) 2010 by Hedera Technology Dev Team (dev@hederatech.com). All rights reserved.
This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
