#!/usr/bin/perl -w
# kanopya-executor - This is the main script to run Kanopya Executor server.

#    Copyright © 2011 Hedera Technology SAS
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Maintained by Dev Team of Hedera Technology <dev@hederatech.com>.
# Created 14 july 2010

=head1 NAME

kanopya-executor - kanopya-executor Server

=head1 SYNOPSIS	    

	$ ./kanopya-executor

=head1 DESCRIPTION

Executor is the main script to run microCluster Executor server.

=head1 METHODS

=cut


use strict;
use warnings;
use Executor;
use Log::Log4perl "get_logger";
use Error qw(:try);

Log::Log4perl->init('/opt/kanopya/conf/executor-log.conf');
my $log = get_logger("executor");


my $running = 1;

sub signalHandler {
	my $sig = shift;
	$log->info($sig." recieved : stopping main loop");
	$running = 0;
}

$SIG{TERM} = \&signalHandler;
	

try	{
	my $exec = Executor->new();
	$log->info("Starting main loop");
	# enter in the main loop and continue while $$running is true
	$exec->run(\$running);
}
catch Error::Simple with {
	my $ex = shift;
	die "Catch error in Executor instanciation: $ex";
};

$log->info("MCExecutor end.");






__END__

=head1 AUTHOR

Copyright (c) 2010 by Hedera Technology Dev Team (dev@hederatech.com). All rights reserved.
This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
