#!/bin/bash -e
wget "http://search.cpan.org/CPAN/authors/id/C/CA/CASIANO/GRID-Machine-0.110.tar.gz"
tar xzf GRID-Machine-0.110.tar.gz
cd GRID-Machine-0.110
perl Makefile.PL INSTALL_BASE=/workspace/tests/GRID-Machine-0.110
make
make test
make install
